apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |
    input {
      http {
        host => "0.0.0.0"
        port => 5044
        user => "${LOGSTASH_USER}"
        password => "${LOGSTASH_PASS}"
      }
    }
    filter {
      mutate {
        remove_field => tags
      }
      json {
        source => "message"
        target => "ace"
        ecs_compatibility => v9
      }
      split { field => "ace" }
    }
    output {
      elasticsearch {
        cloud_id => "${ELASTIC_CLOUD_ID}"
        cloud_auth => "${ELASTIC_CLOUD_AUTH}"
      }
      stdout { codec => rubydebug }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: logstash-secrets
type: Opaque
stringData:
  ELASTIC_CLOUD_ID: "62b6fb70092c48918cc131d31a37c237:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvOjQ0MyQ5YzFhZTRhMzQ4Mjc0MmE3OGI4YzQ0ZmNlZDE5YTQxMSQ5NTE5NTZkODc3Nzk0YmE3YWVkNzIzMzg0NjIwNDRjZg=="
  ELASTIC_CLOUD_AUTH: "elastic:xxxxx"
---
apiVersion: v1
kind: Secret
metadata:
  name: logstash-auth
type: Opaque
stringData:
  LOGSTASH_USER: "loguser"
  LOGSTASH_PASS: "xxxxx"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:9.1.3
        ports:
        - containerPort: 5044
        - containerPort: 5045
        envFrom:
        - secretRef:
            name: logstash-secrets
        - secretRef:
            name: logstash-auth 
        volumeMounts:
        - name: logstash-config
          mountPath: /usr/share/logstash/pipeline/
      volumes:
      - name: logstash-config
        configMap:
          name: logstash-config
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  type: LoadBalancer   # or ClusterIP if only internal
  selector:
    app: logstash
  ports:
    - name: http-input
      port: 5044
      targetPort: 5044
    - name: beats-input
      port: 5045
      targetPort: 5045
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: logstash
spec:
  path: /
  to:
    kind: Service
    name: logstash
    weight: 100
  port:
    targetPort: http-input
  tls:
    termination: edge
  wildcardPolicy: None
